import type { ColorOption } from "@/db/schema";

/** Build a Pexels CDN image URL with a tuned crop. */
export function px(
  id: number,
  opts: { w?: number; h?: number; ext?: "jpeg" | "png" } = {},
): string {
  const { w = 1000, h = 1330, ext = "jpeg" } = opts;
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${ext}?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;
}

type SeedReview = {
  author: string;
  location: string;
  rating: number;
  title: string;
  body: string;
};

type SeedProduct = {
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  story: string;
  category: string;
  gender: string;
  collection: string;
  price: number;
  compareAt?: number;
  colors: ColorOption[];
  sizes: string[];
  sizeType: string;
  images: string[];
  details: string[];
  materials: string;
  care: string;
  badge?: string;
  featured?: boolean;
  newArrival?: boolean;
  bestSeller?: boolean;
  stock: number;
  reviews: SeedReview[];
};

const A = (name: string, hex: string, family: string): ColorOption => ({ name, hex, family });

const ALPHA_W = ["XS", "S", "M", "L", "XL"];
const ALPHA_M = ["S", "M", "L", "XL", "XXL"];
const SHOE_W = ["36", "37", "38", "39", "40", "41"];
const SHOE_M = ["40", "41", "42", "43", "44", "45"];

export const seedCollections = [
  {
    slug: "winter-edit",
    name: "The Winter Edit",
    tagline: "Sculpted outerwear for cold-weather cities",
    description:
      "Double-faced wools, storm-proof cottons and shearling linings cut for long winters in Seoul, Berlin and New York.",
    image: px(19099688, { w: 1200, h: 1500 }),
    accent: "#1c2430",
    sortOrder: 1,
  },
  {
    slug: "elevated-essentials",
    name: "Elevated Essentials",
    tagline: "The everyday layer, reconsidered",
    description:
      "Grade-A cashmere, merino and long-staple cottons in a palette designed to be worn on repeat, season after season.",
    image: px(30569741, { w: 1200, h: 1500 }),
    accent: "#3a3128",
    sortOrder: 2,
  },
  {
    slug: "footwear-atelier",
    name: "The Footwear Atelier",
    tagline: "Hand-finished in Porto",
    description:
      "Vegetable-tanned leathers, Blake-stitched soles and cushioned footbeds built in a family-run atelier in northern Portugal.",
    image: px(12628400, { w: 1200, h: 1500 }),
    accent: "#101215",
    sortOrder: 3,
  },
  {
    slug: "after-hours",
    name: "After Hours",
    tagline: "Evening silhouettes in liquid silk",
    description:
      "Bias-cut slips and column dresses that travel well, pack smaller and hold their drape from dinner to last call.",
    image: px(15272935, { w: 1200, h: 1500 }),
    accent: "#221a20",
    sortOrder: 4,
  },
];

export const seedProducts: SeedProduct[] = [
  {
    slug: "aurora-double-faced-wool-coat",
    name: "Aurora Double-Faced Wool Coat",
    subtitle: "Unlined Italian wool, sculpted shoulder",
    description:
      "A generously cut wrap coat in a double-faced wool from a mill in Biella. The unlined construction keeps the drape soft while the hidden placket and self-tie belt let you shape the silhouette.",
    story:
      "Each Aurora is cut from a single 3.2 metre length of double-faced wool and finished by hand — the seams are tucked and blind-stitched rather than fused, so the coat moves like knitwear.",
    category: "Outerwear",
    gender: "Women",
    collection: "winter-edit",
    price: 690,
    compareAt: 860,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(29879990), px(19099691), px(19099688), px(19169495)],
    details: [
      "Relaxed fit — size down for a closer shape",
      "Hidden press-stud placket with self-tie belt",
      "Angora-soft double-faced wool, 740gsm",
      "Two welt pockets, fully bound interior seams",
    ],
    materials: "82% virgin wool, 18% cashmere. Lining: none (double-faced construction).",
    care: "Dry clean only. Store on a broad wooden hanger.",
    badge: "Atelier",
    featured: true,
    bestSeller: true,
    stock: 24,
    reviews: [
      {
        author: "Maren K.",
        location: "Copenhagen, DK",
        rating: 5,
        title: "Worth every krone",
        body: "The wool is dense but somehow weightless. I've worn it through a Danish February with only a cashmere crew underneath.",
      },
      {
        author: "Priya S.",
        location: "Toronto, CA",
        rating: 5,
        title: "The drape is unreal",
        body: "It falls exactly like the photos. Ordered the Ivory and it has not pilled once after two months of daily wear.",
      },
      {
        author: "Yuki T.",
        location: "Tokyo, JP",
        rating: 4,
        title: "Beautiful, slightly long",
        body: "Gorgeous coat. I'm 163cm so I had the hem taken up 4cm — the tailor commented on the quality of the wool.",
      },
    ],
  },
  {
    slug: "meridian-cotton-trench",
    name: "Meridian Cotton Trench",
    subtitle: "Storm-proof cotton gabardine",
    description:
      "A modern trench with a cleaner shoulder and a longer line, cut in densely woven cotton gabardine that shrugs off a sudden downpour.",
    story:
      "We rebuilt the classic trench block from scratch — dropping the belt loops, raising the collar stand and adding a two-way zip behind the placket so it works on a bike as well as in a taxi.",
    category: "Outerwear",
    gender: "Women",
    collection: "winter-edit",
    price: 540,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Black", "#121212", "Black"), A("Graphite", "#6b6d72", "Grey")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(19099688), px(19099691), px(19138141), px(9571461)],
    details: [
      "Water-repellent finish, PFC-free",
      "Two-way zip beneath a buttoned storm placket",
      "Detachable self-belt with metal buckle",
      "Back vent for movement",
    ],
    materials: "100% cotton gabardine. Trim: recycled polyester twill.",
    care: "Machine wash cold on a gentle cycle. Hang dry.",
    featured: true,
    stock: 31,
    reviews: [
      {
        author: "Elodie B.",
        location: "Lyon, FR",
        rating: 5,
        title: "Rain tested",
        body: "Walked 25 minutes in proper rain and stayed completely dry. It dries in an hour and doesn't wrinkle.",
      },
      {
        author: "Hana A.",
        location: "Dubai, AE",
        rating: 4,
        title: "Great for travel",
        body: "Packs down small and the Graphite is a beautiful deep shade in person. Runs a touch large in the shoulders.",
      },
    ],
  },
  {
    slug: "halo-shearling-bomber",
    name: "Halo Shearling Bomber",
    subtitle: "Recycled shearling, cropped line",
    description:
      "A cropped bomber in plush recycled shearling with a wide shawl collar. Warm enough for -5°C, light enough to drive in.",
    story: "The pile is knitted onto a recycled base rather than woven, which makes it stretchy, breathable and machine washable.",
    category: "Outerwear",
    gender: "Women",
    collection: "winter-edit",
    price: 480,
    compareAt: 560,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Black", "#121212", "Black")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(20264967), px(35117783), px(36185756), px(19169491)],
    details: [
      "Cropped at the high hip",
      "Wide shawl collar and dropped shoulder",
      "Recycled pile on a stretch knit base",
      "Concealed side-entry pockets",
    ],
    materials: "62% recycled polyester, 33% wool, 5% elastane.",
    care: "Machine wash cold, reshape while damp, dry flat.",
    badge: "New",
    newArrival: true,
    stock: 18,
    reviews: [
      {
        author: "Sofia R.",
        location: "Milan, IT",
        rating: 5,
        title: "So soft it feels illegal",
        body: "The pile is genuinely cloud-like and it hasn't shed on black tops at all.",
      },
      {
        author: "Nadia F.",
        location: "Istanbul, TR",
        rating: 4,
        title: "Warm and light",
        body: "Surprised how warm it is for the weight. I would size up if you want to layer a knit under it.",
      },
    ],
  },
  {
    slug: "atlas-wool-overcoat",
    name: "Atlas Wool Overcoat",
    subtitle: "Single-breasted, half-canvassed",
    description:
      "A single-breasted overcoat in a melton wool blend with a half-canvassed chest and a clean, undarted front.",
    story: "Cut slightly shorter than a traditional overcoat so it reads sharp under a tailoring jacket and easy over a hoodie.",
    category: "Outerwear",
    gender: "Men",
    collection: "winter-edit",
    price: 720,
    colors: [A("Graphite", "#6b6d72", "Grey"), A("Charcoal", "#38393c", "Black"), A("Black", "#121212", "Black"), A("Optic White", "#f8f6f2", "White")],
    sizes: ALPHA_M,
    sizeType: "alpha",
    images: [px(28426899), px(29259451), px(21967304), px(19801910)],
    details: [
      "Half-canvassed chest with floating horsehair canvas",
      "Horn-look buttons, working cuff buttons",
      "Interior pocket sized for a phone and passport",
      "Centre back vent, 108cm length in size M",
    ],
    materials: "70% wool, 20% polyamide, 10% cashmere. Lining: cupro.",
    care: "Dry clean only. Brush with a horsehair brush between wears.",
    featured: true,
    stock: 20,
    reviews: [
      {
        author: "Daniel O.",
        location: "Chicago, US",
        rating: 5,
        title: "Beats coats at twice the price",
        body: "The chest has real structure to it — it holds the shoulder line when you sit. Fit is true to size over a shirt.",
      },
      {
        author: "Ken W.",
        location: "Singapore, SG",
        rating: 5,
        title: "Tropical winter travel",
        body: "Bought it for Tokyo in January. Warm, and the Graphite doesn't show rain marks.",
      },
      {
        author: "Anders L.",
        location: "Oslo, NO",
        rating: 4,
        title: "Lovely, sleeves run long",
        body: "Had the sleeves shortened 2cm. Otherwise the best coat I've owned.",
      },
    ],
  },
  {
    slug: "noir-technical-parka",
    name: "Noir Technical Parka",
    subtitle: "3-layer shell, fully taped seams",
    description:
      "A matte three-layer parka with a storm hood, pit zips and a drawcord hem — built for sideways rain and long airport walks.",
    story: "The face fabric is a recycled nylon ripstop with a solvent-free membrane, rated 20k/20k so it breathes on the climb.",
    category: "Outerwear",
    gender: "Unisex",
    collection: "winter-edit",
    price: 640,
    colors: [A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black"), A("Graphite", "#6b6d72", "Grey")],
    sizes: ALPHA_M,
    sizeType: "alpha",
    images: [px(19801910), px(21967304), px(29037366), px(16845071)],
    details: [
      "20,000mm waterproof / 20,000g breathability",
      "Fully taped seams and water-resistant zips",
      "Adjustable storm hood with a stiffened brim",
      "Packs into its own left pocket",
    ],
    materials: "100% recycled nylon ripstop with a PFC-free membrane.",
    care: "Machine wash cold with technical detergent. Do not tumble dry.",
    newArrival: true,
    stock: 27,
    reviews: [
      {
        author: "Tom H.",
        location: "Manchester, UK",
        rating: 5,
        title: "Manchester approved",
        body: "If it survives a Mancunian winter it survives anything. Genuinely waterproof.",
      },
      {
        author: "Ines M.",
        location: "Lisbon, PT",
        rating: 5,
        title: "Slick and quiet",
        body: "Not crinkly like most shells. The Black is a proper deep matte.",
      },
    ],
  },
  {
    slug: "cloudsoft-cashmere-crew",
    name: "Cloudsoft Cashmere Crew",
    subtitle: "Grade-A Mongolian cashmere, 4-ply",
    description:
      "A four-ply cashmere crew with ribbed edges and a slightly relaxed body. The fibres are 36mm long, which is why it never itches.",
    story: "Knitted in Inner Mongolia on vintage flat-bed machines at a low tension, then washed in soft water for 40 minutes to bloom the halo.",
    category: "Knitwear",
    gender: "Women",
    collection: "elevated-essentials",
    price: 320,
    compareAt: 395,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Charcoal", "#38393c", "Black"), A("Black", "#121212", "Black")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(6995886), px(24740436), px(29865096), px(30569741)],
    details: [
      "4-ply, 620gsm Grade-A cashmere",
      "Fully fashioned shoulders — no bulky seams",
      "Ribbed collar, cuffs and hem",
      "Relaxed body, sleeves cut to the wrist bone",
    ],
    materials: "100% Grade-A Mongolian cashmere.",
    care: "Hand wash cool with cashmere shampoo. Dry flat away from heat.",
    featured: true,
    bestSeller: true,
    stock: 42,
    reviews: [
      {
        author: "Claire D.",
        location: "Melbourne, AU",
        rating: 5,
        title: "Third one",
        body: "I now own this in three colours. Two winters in, the first one still looks new.",
      },
      {
        author: "Anita V.",
        location: "Berlin, DE",
        rating: 5,
        title: "Not itchy at all",
        body: "I have very reactive skin and this is the only cashmere I can wear against bare skin.",
      },
      {
        author: "Lucia P.",
        location: "Buenos Aires, AR",
        rating: 4,
        title: "Size up for slouch",
        body: "True to size, but I like it oversized so I went up one and it's perfect.",
      },
    ],
  },
  {
    slug: "ribbed-merino-turtleneck",
    name: "Ribbed Merino Turtleneck",
    subtitle: "Extra-fine 19.5 micron merino",
    description:
      "A fine-gauge ribbed turtleneck that layers flat under tailoring but reads as a statement on its own.",
    story: "Knitted in a 3x1 rib with a touch of elastane so the collar keeps standing after the tenth wear.",
    category: "Knitwear",
    gender: "Women",
    collection: "elevated-essentials",
    price: 245,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Black", "#121212", "Black"), A("Navy", "#222d42", "Blue")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(6995884), px(6995898), px(6996083), px(14641430)],
    details: [
      "Extra-fine 19.5 micron merino, machine washable",
      "Self-standing ribbed collar",
      "Sleeveless-friendly cropped hip length",
      "Fully reversible silhouette",
    ],
    materials: "96% extra-fine merino wool, 4% elastane.",
    care: "Machine wash wool cycle at 30°C. Dry flat.",
    bestSeller: true,
    stock: 56,
    reviews: [
      {
        author: "Rosa M.",
        location: "Madrid, ES",
        rating: 5,
        title: "The perfect base layer",
        body: "Disappears under a blazer and the collar doesn't slouch. I'm on my second.",
      },
      {
        author: "Julia N.",
        location: "Warsaw, PL",
        rating: 4,
        title: "Great, slightly sheer",
        body: "In Optic White it needs a skin-tone bra. Navy is fully opaque.",
      },
    ],
  },
  {
    slug: "atelier-oversized-cardigan",
    name: "Atelier Oversized Cardigan",
    subtitle: "Chunky cable front, drop shoulder",
    description:
      "A generously oversized cardigan with deep patch pockets, meant to be worn open as a house coat or belt as outerwear.",
    story: "The yarn is a wool-cotton blend spun in Tuscany, giving cable definition without the weight of pure lambswool.",
    category: "Knitwear",
    gender: "Unisex",
    collection: "elevated-essentials",
    price: 285,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Black", "#121212", "Black"), A("Moss", "#4a5343", "Green")],
    sizes: ["S", "M", "L"],
    sizeType: "alpha",
    images: [px(9603626), px(29865096), px(14641430), px(24740436)],
    details: [
      "Oversized — take your usual size for a relaxed fit",
      "Deep patch pockets and dropped shoulders",
      "Corozo nut buttons",
      "Cable-front panel with plain sleeves",
    ],
    materials: "55% wool, 40% cotton, 5% alpaca.",
    care: "Hand wash cool or dry clean. Dry flat.",
    stock: 33,
    reviews: [
      {
        author: "Freya L.",
        location: "Reykjavik, IS",
        rating: 5,
        title: "My whole winter",
        body: "Enormous, cosy and the Ivory colour is beautiful. Wears like a coat indoors.",
      },
      {
        author: "Mark J.",
        location: "Portland, US",
        rating: 5,
        title: "Bought the Moss",
        body: "Great neutral green, not too bright. Buttons feel solid.",
      },
    ],
  },
  {
    slug: "heritage-cable-knit",
    name: "Heritage Cable Knit",
    subtitle: "Lambswool fisherman knit",
    description:
      "A traditional fisherman's cable knit with saddle shoulders and a high neck, updated with a slightly slimmer sleeve.",
    story: "Knitted in a Scottish mill that has been making ganseys since 1874, using lambswool from the Borders.",
    category: "Knitwear",
    gender: "Men",
    collection: "elevated-essentials",
    price: 265,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Charcoal", "#38393c", "Black"), A("Navy", "#1f2942", "Blue")],
    sizes: ALPHA_M,
    sizeType: "alpha",
    images: [px(12056642), px(30569741), px(14641430), px(9603626)],
    details: [
      "Saddle shoulder for a fuller chest",
      "Traditional honeycomb and cable panels",
      "Ribbed funnel neck",
      "Naturally water-resistant lanolin-rich wool",
    ],
    materials: "100% British lambswool.",
    care: "Hand wash cool. Dry flat. Refresh in fresh air between wears.",
    stock: 29,
    reviews: [
      {
        author: "Callum R.",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Proper jumper",
        body: "Heavy, warm and the lanolin smell is oddly nostalgic. Exactly what I hoped for.",
      },
      {
        author: "Theo K.",
        location: "Vancouver, CA",
        rating: 4,
        title: "Chunky",
        body: "Very substantial knit — a real winter piece rather than a layering one.",
      },
    ],
  },
  {
    slug: "nova-court-leather-sneaker",
    name: "Nova Court Leather Sneaker",
    subtitle: "Italian calfskin, cupsole",
    description:
      "A pared-back court sneaker in full-grain Italian calfskin on a hand-stitched cupsole. No logos, no branding — just the shape.",
    story: "The upper is cut from a single hide so the grain runs continuously down the vamp, then Blake-stitched to the sole so it can be resoled.",
    category: "Footwear",
    gender: "Unisex",
    collection: "footwear-atelier",
    price: 240,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Black", "#121212", "Black")],
    sizes: SHOE_M,
    sizeType: "shoe",
    images: [px(7193629), px(18202585), px(7193625), px(12628400)],
    details: [
      "Full-grain calfskin from a Tuscan tannery",
      "Blake-stitched, fully resoleable cupsole",
      "Removable moulded footbed with arch support",
      "Runs true to size; half sizes coming soon",
    ],
    materials: "Upper: Italian calfskin. Lining: vegetable-tanned leather. Sole: natural rubber.",
    care: "Wipe with a damp cloth. Condition every 8-10 wears.",
    featured: true,
    bestSeller: true,
    stock: 48,
    reviews: [
      {
        author: "Wei C.",
        location: "Taipei, TW",
        rating: 5,
        title: "Zero break-in",
        body: "Wore them for a 12-hour travel day straight out of the box. No blisters, no heel slip.",
      },
      {
        author: "Sasha G.",
        location: "Brooklyn, US",
        rating: 5,
        title: "The white sneaker, done right",
        body: "Clean toe box, no branding, and the leather has started to patina beautifully.",
      },
      {
        author: "Omar D.",
        location: "Casablanca, MA",
        rating: 4,
        title: "Narrow-ish",
        body: "Slightly narrow through the midfoot. Fine for me, but wide-footed friends should size up.",
      },
    ],
  },
  {
    slug: "trace-runner",
    name: "Trace Runner",
    subtitle: "Recycled knit upper, foam midsole",
    description:
      "A low-profile everyday runner in a seamless recycled knit with a supercritical foam midsole and a 6mm drop.",
    story: "Weighs 218g in a size 42. The midsole foam is nitrogen-injected, so it stays lively past 600km.",
    category: "Footwear",
    gender: "Unisex",
    collection: "footwear-atelier",
    price: 210,
    compareAt: 250,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Graphite", "#6b6d72", "Grey"), A("Black", "#121212", "Black")],
    sizes: SHOE_M,
    sizeType: "shoe",
    images: [px(8188879), px(20191568), px(20191567), px(18202585)],
    details: [
      "218g (size 42)",
      "6mm heel-to-toe drop",
      "Seamless recycled knit upper — no tongue break",
      "Nitrogen-injected supercritical foam",
    ],
    materials: "Upper: 92% recycled polyester knit. Midsole: EVA/TPU blend. Outsole: recycled rubber.",
    care: "Hand wash upper with mild soap. Air dry.",
    bestSeller: true,
    stock: 61,
    reviews: [
      {
        author: "Lena S.",
        location: "Amsterdam, NL",
        rating: 5,
        title: "City miles",
        body: "Bouncy but stable. I've done 300km including cobblestones and the foam still feels new.",
      },
      {
        author: "Ravi P.",
        location: "Bengaluru, IN",
        rating: 5,
        title: "Breathes in 32°C",
        body: "The knit is genuinely airy. No hot spots.",
      },
    ],
  },
  {
    slug: "pop-court-sneaker",
    name: "Pop Court Sneaker",
    subtitle: "Colour-blocked suede and mesh",
    description:
      "The Court's louder sibling: colour-blocked suede overlays on a breathable mesh base with a gum rubber outsole.",
    story: "Developed with a small studio in Porto that specialises in hand-burnished suede panels.",
    category: "Footwear",
    gender: "Unisex",
    collection: "footwear-atelier",
    price: 195,
    colors: [A("Cobalt", "#2b4c9b", "Blue"), A("Signal Red", "#b8342c", "Red"), A("Optic White", "#f6f4f0", "White")],
    sizes: SHOE_M,
    sizeType: "shoe",
    images: [px(11324546), px(11324526), px(14525666), px(20191567)],
    details: [
      "Hand-burnished suede overlays",
      "Gum rubber outsole with a herringbone tread",
      "Padded collar and cushioned insole",
      "Sizing: generous — consider going down a half size",
    ],
    materials: "Upper: pig suede and recycled mesh. Outsole: natural gum rubber.",
    care: "Brush suede dry. Protect with a suede spray before first wear.",
    badge: "Limited",
    newArrival: true,
    stock: 22,
    reviews: [
      {
        author: "Nina B.",
        location: "Seoul, KR",
        rating: 5,
        title: "Photos don't do the colour",
        body: "The Cobalt is electric in person. Got stopped twice on the first day.",
      },
      {
        author: "Jonas E.",
        location: "Hamburg, DE",
        rating: 4,
        title: "Fun shoe",
        body: "Comfortable straight away. Suede marks easily, so treat it.",
      },
    ],
  },
  {
    slug: "meridian-chelsea-boot",
    name: "Meridian Chelsea Boot",
    subtitle: "Vegetable-tanned leather, chunky sole",
    description:
      "A city Chelsea boot in vegetable-tanned leather with elasticated gussets and a lug sole that actually grips on wet stone.",
    story: "The last is based on a 1960s Italian motoring boot — narrow at the waist, generous at the toe.",
    category: "Footwear",
    gender: "Women",
    collection: "footwear-atelier",
    price: 420,
    colors: [A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black"), A("Graphite", "#6b6d72", "Grey")],
    sizes: SHOE_W,
    sizeType: "shoe",
    images: [px(18911766), px(12586098), px(34235456), px(11332376)],
    details: [
      "Vegetable-tanned leather, 1.8mm thickness",
      "Blake-stitched with a storm welt",
      "Dual-density rubber lug sole, 25mm",
      "Leather-lined with a padded footbed",
    ],
    materials: "Upper and lining: vegetable-tanned Italian leather. Sole: rubber/cork composite.",
    care: "Condition monthly. Use a cedar shoe tree between wears.",
    featured: true,
    stock: 26,
    reviews: [
      {
        author: "Amélie R.",
        location: "Paris, FR",
        rating: 5,
        title: "Paris-proof",
        body: "Survived a week of rain on paving stones with zero slipping. The leather is thick and gorgeous.",
      },
      {
        author: "Grace T.",
        location: "Sydney, AU",
        rating: 5,
        title: "Elegant and tough",
        body: "Rare to find a lug sole that doesn't look clunky. These read sleek under trousers.",
      },
      {
        author: "Mira H.",
        location: "Stockholm, SE",
        rating: 4,
        title: "Stiff at first",
        body: "Three wears to break in, then excellent. Order your usual size.",
      },
    ],
  },
  {
    slug: "solstice-knee-boot",
    name: "Solstice Knee Boot",
    subtitle: "Stretch leather, sculpted heel",
    description:
      "A knee-high boot in a stretch leather that hugs the calf without a zip, set on a sculpted 60mm block heel.",
    story: "The stretch comes from a bonded knit back, not from thin leather, so it keeps its shape all day.",
    category: "Footwear",
    gender: "Women",
    collection: "footwear-atelier",
    price: 520,
    colors: [A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black")],
    sizes: SHOE_W,
    sizeType: "shoe",
    images: [px(32366927), px(7062176), px(19120507), px(10910252)],
    details: [
      "Zip-free pull-on construction",
      "60mm sculpted block heel",
      "Circumference 36cm at the top (size 38)",
      "Softly squared almond toe",
    ],
    materials: "Upper: stretch lambskin on a knit back. Sole: leather with a rubber toplift.",
    care: "Wipe clean. Store upright with boot shapers.",
    badge: "Runway",
    featured: true,
    stock: 15,
    reviews: [
      {
        author: "Bianca F.",
        location: "New York, US",
        rating: 5,
        title: "No zip, no gaping",
        body: "They actually stay up on my calves, which never happens. Wore them for 10 hours at a trade show.",
      },
      {
        author: "Aiko M.",
        location: "Osaka, JP",
        rating: 5,
        title: "Sculptural",
        body: "The heel is a work of art. Comfortable for a 60mm boot.",
      },
    ],
  },
  {
    slug: "terrace-leather-loafer",
    name: "Terrace Leather Loafer",
    subtitle: "Hand-sewn apron, flexible sole",
    description:
      "An unlined apron-toe loafer that's built to be worn without socks and thrown in a bag for travel.",
    story: "The apron is sewn by hand with a saddle stitch, which is why it moulds to your foot within a week.",
    category: "Footwear",
    gender: "Unisex",
    collection: "footwear-atelier",
    price: 310,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Black", "#121212", "Black"), A("Graphite", "#6b6d72", "Grey")],
    sizes: SHOE_M,
    sizeType: "shoe",
    images: [px(11332376), px(12586098), px(34235456), px(8411014)],
    details: [
      "Hand-sewn apron with a saddle stitch",
      "Unlined for a barefoot feel",
      "Flexible rubber-city sole",
      "Sizing: runs large — size down half",
    ],
    materials: "Upper: vegetable-tanned calf. Sole: flexible rubber.",
    care: "Wipe with a damp cloth. Cream polish occasionally.",
    stock: 34,
    reviews: [
      {
        author: "Léa C.",
        location: "Geneva, CH",
        rating: 5,
        title: "Moulds to your foot",
        body: "Unlined leather sounds odd but after a week it felt custom-made.",
      },
      {
        author: "Peter V.",
        location: "Auckland, NZ",
        rating: 4,
        title: "Great, size down",
        body: "Definitely half a size large. The Optic White is crisp and clean.",
      },
    ],
  },
  {
    slug: "liquid-silk-slip-dress",
    name: "Liquid Silk Slip Dress",
    subtitle: "22-momme bias-cut mulberry silk",
    description:
      "A bias-cut slip in heavyweight 22-momme mulberry silk that skims rather than clings, with adjustable straps.",
    story: "Cut on the true bias from a single panel so the dress spirals around the body — there are only two seams.",
    category: "Dresses",
    gender: "Women",
    collection: "after-hours",
    price: 380,
    compareAt: 450,
    colors: [A("Black", "#121212", "Black"), A("Ivory", "#eae3d6", "White"), A("Bordeaux", "#5d1f2b", "Red")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(15272935), px(20821761), px(5822538), px(17541235)],
    details: [
      "22-momme mulberry silk, matte finish",
      "True bias cut with French seams",
      "Adjustable sliders on the straps",
      "Midi length, 118cm centre back",
    ],
    materials: "100% mulberry silk, OEKO-TEX certified.",
    care: "Dry clean recommended, or hand wash cold with silk detergent.",
    featured: true,
    bestSeller: true,
    stock: 25,
    reviews: [
      {
        author: "Stella M.",
        location: "Los Angeles, US",
        rating: 5,
        title: "Actually opaque",
        body: "The 22-momme weight makes all the difference — no underwear show-through, and it doesn't crease like cheaper silk.",
      },
      {
        author: "Farah K.",
        location: "Doha, QA",
        rating: 5,
        title: "Wedding guest winner",
        body: "Wore the Bordeaux to a wedding, packed it in a carry-on and it came out without a crease.",
      },
      {
        author: "Ivy L.",
        location: "London, UK",
        rating: 4,
        title: "Long on petite frames",
        body: "Gorgeous, but I'm 5'3\" and it's ankle length. Had it shortened 6cm.",
      },
    ],
  },
  {
    slug: "sunlight-linen-shirt-dress",
    name: "Sunlight Linen Shirt Dress",
    subtitle: "Washed European linen",
    description:
      "A shirt dress in garment-washed European linen with a detachable belt and a deep back pleat for movement.",
    story: "The linen is woven in Normandy and washed three times before cutting, so it arrives already soft.",
    category: "Dresses",
    gender: "Women",
    collection: "elevated-essentials",
    price: 265,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Sky", "#a7bcd0", "Blue")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(20117711), px(37291294), px(12466607), px(34891485)],
    details: [
      "Garment-washed Normandy linen, 190gsm",
      "Detachable self-belt",
      "Deep back box pleat",
      "Mother-of-pearl buttons",
    ],
    materials: "100% European flax linen.",
    care: "Machine wash cold. Tumble dry low to soften.",
    newArrival: true,
    stock: 38,
    reviews: [
      {
        author: "Marta G.",
        location: "Barcelona, ES",
        rating: 5,
        title: "Summer uniform",
        body: "Lives in my suitcase from May to September. Breathes beautifully at 35°C.",
      },
      {
        author: "Ellie W.",
        location: "Cape Town, ZA",
        rating: 4,
        title: "Lovely, creases",
        body: "It's linen, so it creases — but that's the look. The Optic White is beautifully crisp.",
      },
    ],
  },
  {
    slug: "ivory-column-dress",
    name: "Ivory Column Dress",
    subtitle: "Crepe column, open back",
    description:
      "A floor-sweeping column in heavy crepe with a square neckline and an open, cowl-hung back.",
    story: "Internally boned through the bodice so it holds its line without a bra, and hemmed by hand.",
    category: "Dresses",
    gender: "Women",
    collection: "after-hours",
    price: 620,
    colors: [A("Ivory", "#f2ece1", "White"), A("Midnight", "#161a28", "Blue")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(28442112), px(34891485), px(34896846), px(5822538)],
    details: [
      "Internally boned bodice with a shelf bra",
      "Square front neckline, cowl back",
      "Heavy stretch crepe, 320gsm",
      "Floor length, hand-finished hem",
    ],
    materials: "78% triacetate, 22% polyester crepe.",
    care: "Dry clean only. Steam to release creases.",
    stock: 14,
    reviews: [
      {
        author: "Chloe A.",
        location: "Sydney, AU",
        rating: 5,
        title: "Wore it to a gala",
        body: "Three people asked who made it. The internal boning means no bra, no fuss.",
      },
      {
        author: "Noor S.",
        location: "Amman, JO",
        rating: 5,
        title: "Sculpted",
        body: "The crepe holds you in without being tight. True to size.",
      },
    ],
  },
  {
    slug: "rose-satin-gown",
    name: "Rose Satin Gown",
    subtitle: "Draped cowl, floor length",
    description:
      "A liquid satin gown with a softly draped cowl front and a low, gathered back. Made for photographs.",
    story: "The satin is a heavy 40d trilobal that reflects light in a soft halo rather than a hard shine.",
    category: "Dresses",
    gender: "Women",
    collection: "after-hours",
    price: 540,
    colors: [A("Rose", "#d9a2a4", "Pink"), A("Black", "#131114", "Black")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(34896846), px(5822538), px(34891485), px(28442112)],
    details: [
      "Draped cowl front and back",
      "Hidden side zip with a hook-and-eye",
      "Floor length with a slight train",
      "Cut on the bias through the skirt",
    ],
    materials: "100% trilobal polyester satin with a matte crepe back.",
    care: "Dry clean only. Store hanging.",
    newArrival: true,
    stock: 17,
    reviews: [
      {
        author: "Zoe H.",
        location: "Austin, US",
        rating: 5,
        title: "The Rose colour",
        body: "Somewhere between blush and mauve — far more sophisticated than the photos suggest.",
      },
      {
        author: "Isabel R.",
        location: "Mexico City, MX",
        rating: 4,
        title: "Needs heels",
        body: "Very long, so plan on heels or a hem. Beautiful drape.",
      },
    ],
  },
  {
    slug: "sculpt-wool-blazer",
    name: "Sculpt Wool Blazer",
    subtitle: "Half-canvassed, sharp shoulder",
    description:
      "A single-breasted blazer with a lightly padded shoulder, nipped waist and a length that hits at the high hip.",
    story: "The shoulder is built with a thin wadding layer rather than a rope, so it reads strong but not 80s.",
    category: "Tailoring",
    gender: "Women",
    collection: "elevated-essentials",
    price: 480,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black"), A("Bottle", "#22352c", "Green")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(27869836), px(39202946), px(15127334), px(19222080)],
    details: [
      "Half-canvassed with a floating chest canvas",
      "Lightly padded shoulder, two-button front",
      "Functional cuff buttons",
      "Bemberg cupro lining",
    ],
    materials: "96% wool, 4% elastane suiting. Lining: cupro.",
    care: "Dry clean only. Press on a tailor's ham.",
    featured: true,
    stock: 30,
    reviews: [
      {
        author: "Helen Z.",
        location: "Singapore, SG",
        rating: 5,
        title: "Office to dinner",
        body: "The waist is properly nipped so it doesn't look boxy over a dress. Excellent in humid weather.",
      },
      {
        author: "Dana Q.",
        location: "Dublin, IE",
        rating: 5,
        title: "Best tailoring I own",
        body: "The shoulder line is perfect. I've had it taken in slightly at the waist for a made-to-measure feel.",
      },
    ],
  },
  {
    slug: "wide-leg-pleated-trouser",
    name: "Wide-Leg Pleated Trouser",
    subtitle: "Fluid drape, high rise",
    description:
      "A high-rise, double-pleated trouser in a fluid wool blend that falls straight from the hip to a full break.",
    story: "We tested eleven drafts before landing on a leg that reads wide but doesn't swamp a smaller frame.",
    category: "Tailoring",
    gender: "Women",
    collection: "elevated-essentials",
    price: 260,
    colors: [A("Black", "#121212", "Black"), A("Optic White", "#f8f6f2", "White"), A("Navy", "#212b40", "Blue")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(22223037), px(27869836), px(8891480, { ext: "png" }), px(39202946)],
    details: [
      "High rise with a hidden hook closure",
      "Double front pleats",
      "Full-length wide leg, 30cm opening",
      "Unhemmed — free tailoring in-store",
    ],
    materials: "68% wool, 30% viscose, 2% elastane.",
    care: "Dry clean. Steam the pleats back in after travel.",
    bestSeller: true,
    stock: 44,
    reviews: [
      {
        author: "Tara N.",
        location: "Toronto, CA",
        rating: 5,
        title: "Finally, a wide leg that works",
        body: "I'm 5'2\" and these don't drown me with a 3cm heel. The drape is beautiful.",
      },
      {
        author: "Sara K.",
        location: "Dubai, AE",
        rating: 4,
        title: "Great fabric",
        body: "Doesn't wrinkle on long flights. Needed a belt as the waist runs slightly big.",
      },
    ],
  },
  {
    slug: "essential-pima-tee",
    name: "Essential Pima Tee",
    subtitle: "Long-staple Peruvian pima",
    description:
      "A mid-weight tee in long-staple Peruvian pima with a clean bound neckline that won't stretch out.",
    story: "Knitted at 200gsm, so it's opaque enough to wear alone and smooth enough to layer under tailoring.",
    category: "Essentials",
    gender: "Unisex",
    collection: "elevated-essentials",
    price: 85,
    colors: [A("Optic White", "#f8f6f2", "White"), A("Ivory", "#eae3d6", "White"), A("Black", "#121212", "Black"), A("Sage", "#a9b3a0", "Green")],
    sizes: ALPHA_M,
    sizeType: "alpha",
    images: [px(18516744), px(18516754), px(19771909), px(19222080)],
    details: [
      "200gsm long-staple Peruvian pima",
      "Bound neckline, twin-needle hems",
      "Pre-shrunk and bio-washed",
      "Boxy but not cropped",
    ],
    materials: "100% Peruvian pima cotton.",
    care: "Machine wash cold. Tumble dry low.",
    bestSeller: true,
    stock: 120,
    reviews: [
      {
        author: "Kate O.",
        location: "Auckland, NZ",
        rating: 5,
        title: "Bought five",
        body: "The neck hasn't stretched after months of washing. Worth the price over cheap tees.",
      },
      {
        author: "Ben A.",
        location: "Berlin, DE",
        rating: 5,
        title: "Perfect weight",
        body: "Not see-through, not stiff. The Sage is a great soft green.",
      },
      {
        author: "Rina D.",
        location: "Jakarta, ID",
        rating: 4,
        title: "Good, boxy fit",
        body: "Very boxy through the body. I sized down and love it.",
      },
    ],
  },
  {
    slug: "noir-evening-dress",
    name: "Noir Evening Dress",
    subtitle: "Structured bodice, draped skirt",
    description:
      "A black evening dress with a structured strapless bodice and a softly draped skirt that catches light as you move.",
    story: "The bodice is bonded rather than boned, giving structure without any rigidity at the ribcage.",
    category: "Dresses",
    gender: "Women",
    collection: "after-hours",
    price: 560,
    colors: [A("Black", "#121212", "Black"), A("Charcoal", "#38393c", "Black")],
    sizes: ALPHA_W,
    sizeType: "alpha",
    images: [px(29977336), px(17541235), px(20821761), px(19771909)],
    details: [
      "Bonded structured bodice",
      "Strapless with a silicone grip line",
      "Draped skirt with a concealed side zip",
      "Midi length with an asymmetric hem",
    ],
    materials: "92% recycled polyester crepe, 8% elastane.",
    care: "Dry clean only.",
    stock: 12,
    reviews: [
      {
        author: "Vivian L.",
        location: "Hong Kong, HK",
        rating: 5,
        title: "Stays put",
        body: "Danced for four hours without once pulling it up. That never happens with a strapless.",
      },
      {
        author: "Camille R.",
        location: "Montreal, CA",
        rating: 5,
        title: "Sculptural",
        body: "Looks like couture from the front and the back. Very flattering.",
      },
    ],
  },
  {
    slug: "atlas-denim-jacket",
    name: "Atlas Denim Jacket",
    subtitle: "Selvedge denim, Kyoto loom",
    description:
      "A boxy denim jacket in 13oz selvedge denim woven on shuttle looms in Okayama, cut to layer over knitwear.",
    story: "Unwashed and rigid at first, it fades to your body within three months of daily wear.",
    category: "Outerwear",
    gender: "Unisex",
    collection: "elevated-essentials",
    price: 290,
    colors: [A("Rinse Indigo", "#26364f", "Blue"), A("Washed Black", "#232326", "Black")],
    sizes: ALPHA_M,
    sizeType: "alpha",
    images: [px(15299304), px(29197620), px(21967310), px(19338688, { ext: "png" })],
    details: [
      "13oz unsanforized selvedge denim from Okayama",
      "Boxy cut with a slightly longer body",
      "Copper rivets and a chain-stitched hem",
      "Rigid — expect 2cm shrink on first wash",
    ],
    materials: "100% cotton selvedge denim.",
    care: "Wash rarely, cold, inside out. Hang dry in the shade.",
    stock: 36,
    reviews: [
      {
        author: "Hiro S.",
        location: "Okayama, JP",
        rating: 5,
        title: "The real thing",
        body: "Proper shuttle-loom denim. Heavy, slubby and it's already starting to fade at the elbows.",
      },
      {
        author: "Maya J.",
        location: "Berlin, DE",
        rating: 4,
        title: "Size up",
        body: "Very boxy. I sized up for layering and it's perfect over the Cloudsoft crew.",
      },
    ],
  },
];
